# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  - name: repository
    value: 'rianalytics'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: containerRegistry
    value: 'docker137'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push docker image
      inputs:
        command: buildAndPush
        repository: ${{ variables.repository }}
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: ${{ variables.containerRegistry }}
        tags: $(Build.BuildID)
