# Generated by Django 4.0 on 2022-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_analytics', '0002_socialanalyticsmodel_handles_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialanalyticsmodel',
            name='handles_files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
