name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # Working cicd
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M')"
    - name: Build the Docker image
      run: docker build . --tag dhairya137/rianalytics:dev-${{ steps.date.outputs.date }}
      
    - name: Docker Push
      run: docker push dhairya137/rianalytics:dev${{ steps.date.outputs.date }}
      
      
  push:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Remote ssh into VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker rm -f rianalytics
          sudo docker run --name=rianalytics -p 80:8000 dhairya137/rianalytics:dev${{ steps.date.outputs.date }}
          echo "App is runnning fine..."
