name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    -        
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    - name: Build the Docker image
      run: docker build --tag dhairya137/rianalytics:$(date +%s) .
      
    - name: Docker Push
      run: docker push dhairya137/rianalytics
