name: Trigger auto deployment for rianalytics

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/rianalytics-AutoDeployTrigger-3bf43cb6-d5eb-4bd8-8f7e-23e38061707b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: rianalytics.azurecr.io
          username: ${{ secrets.RIANALYTICS_REGISTRY_USERNAME }}
          password: ${{ secrets.RIANALYTICS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rianalytics.azurecr.io/app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RIANALYTICS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n rianalytics -g rianalytics --server rianalytics.azurecr.io --username  ${{ secrets.RIANALYTICS_REGISTRY_USERNAME }} --password ${{ secrets.RIANALYTICS_REGISTRY_PASSWORD }}
            az containerapp update -n rianalytics -g rianalytics --image rianalytics.azurecr.io/app:${{ github.sha }}
